# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artifact.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='artifact.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x61rtifact.proto\"\x9c\x02\n\x10\x41rtifactMetadata\x12$\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x16.ArtifactMetadata.Data\x12\x14\n\x0c\x64\x65rived_from\x18\x03 \x03(\t\x1a\xcb\x01\n\x04\x44\x61ta\x12\x39\n\x0fglsl_shader_job\x18\x01 \x01(\x0b\x32\x1e.ArtifactMetadataGlslShaderJobH\x00\x12\x43\n\x19glsl_shader_job_reduction\x18\x02 \x01(\x0b\x32\x1e.ArtifactMetadataGlslReductionH\x00\x12;\n\x10spirv_shader_job\x18\x03 \x01(\x0b\x32\x1f.ArtifactMetadataSpirvShaderJobH\x00\x42\x06\n\x04\x64\x61ta\"d\n\x1d\x41rtifactMetadataGlslShaderJob\x12\x17\n\x0fshader_job_file\x18\x01 \x01(\t\x12*\n\"reference_glsl_shader_job_artifact\x18\x02 \x01(\t\"5\n\x1d\x41rtifactMetadataGlslReduction\x12\x14\n\x0c\x66inal_shader\x18\x01 \x01(\t\"u\n\x1e\x41rtifactMetadataSpirvShaderJob\x12\x17\n\x0fshader_job_file\x18\x01 \x01(\t\x12\'\n\x1fglsl_shader_job_source_artifact\x18\x02 \x01(\t\x12\x11\n\toptimized\x18\x03 \x01(\x08\".\n\x18\x41rtifactMetadataAmberJob\x12\x12\n\namber_file\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ARTIFACTMETADATA_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='ArtifactMetadata.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='glsl_shader_job', full_name='ArtifactMetadata.Data.glsl_shader_job', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glsl_shader_job_reduction', full_name='ArtifactMetadata.Data.glsl_shader_job_reduction', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spirv_shader_job', full_name='ArtifactMetadata.Data.spirv_shader_job', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='ArtifactMetadata.Data.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=100,
  serialized_end=303,
)

_ARTIFACTMETADATA = _descriptor.Descriptor(
  name='ArtifactMetadata',
  full_name='ArtifactMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ArtifactMetadata.data', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='derived_from', full_name='ArtifactMetadata.derived_from', index=1,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ARTIFACTMETADATA_DATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=303,
)


_ARTIFACTMETADATAGLSLSHADERJOB = _descriptor.Descriptor(
  name='ArtifactMetadataGlslShaderJob',
  full_name='ArtifactMetadataGlslShaderJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shader_job_file', full_name='ArtifactMetadataGlslShaderJob.shader_job_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reference_glsl_shader_job_artifact', full_name='ArtifactMetadataGlslShaderJob.reference_glsl_shader_job_artifact', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=405,
)


_ARTIFACTMETADATAGLSLREDUCTION = _descriptor.Descriptor(
  name='ArtifactMetadataGlslReduction',
  full_name='ArtifactMetadataGlslReduction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='final_shader', full_name='ArtifactMetadataGlslReduction.final_shader', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=460,
)


_ARTIFACTMETADATASPIRVSHADERJOB = _descriptor.Descriptor(
  name='ArtifactMetadataSpirvShaderJob',
  full_name='ArtifactMetadataSpirvShaderJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shader_job_file', full_name='ArtifactMetadataSpirvShaderJob.shader_job_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glsl_shader_job_source_artifact', full_name='ArtifactMetadataSpirvShaderJob.glsl_shader_job_source_artifact', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optimized', full_name='ArtifactMetadataSpirvShaderJob.optimized', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=579,
)


_ARTIFACTMETADATAAMBERJOB = _descriptor.Descriptor(
  name='ArtifactMetadataAmberJob',
  full_name='ArtifactMetadataAmberJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amber_file', full_name='ArtifactMetadataAmberJob.amber_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=627,
)

_ARTIFACTMETADATA_DATA.fields_by_name['glsl_shader_job'].message_type = _ARTIFACTMETADATAGLSLSHADERJOB
_ARTIFACTMETADATA_DATA.fields_by_name['glsl_shader_job_reduction'].message_type = _ARTIFACTMETADATAGLSLREDUCTION
_ARTIFACTMETADATA_DATA.fields_by_name['spirv_shader_job'].message_type = _ARTIFACTMETADATASPIRVSHADERJOB
_ARTIFACTMETADATA_DATA.containing_type = _ARTIFACTMETADATA
_ARTIFACTMETADATA_DATA.oneofs_by_name['data'].fields.append(
  _ARTIFACTMETADATA_DATA.fields_by_name['glsl_shader_job'])
_ARTIFACTMETADATA_DATA.fields_by_name['glsl_shader_job'].containing_oneof = _ARTIFACTMETADATA_DATA.oneofs_by_name['data']
_ARTIFACTMETADATA_DATA.oneofs_by_name['data'].fields.append(
  _ARTIFACTMETADATA_DATA.fields_by_name['glsl_shader_job_reduction'])
_ARTIFACTMETADATA_DATA.fields_by_name['glsl_shader_job_reduction'].containing_oneof = _ARTIFACTMETADATA_DATA.oneofs_by_name['data']
_ARTIFACTMETADATA_DATA.oneofs_by_name['data'].fields.append(
  _ARTIFACTMETADATA_DATA.fields_by_name['spirv_shader_job'])
_ARTIFACTMETADATA_DATA.fields_by_name['spirv_shader_job'].containing_oneof = _ARTIFACTMETADATA_DATA.oneofs_by_name['data']
_ARTIFACTMETADATA.fields_by_name['data'].message_type = _ARTIFACTMETADATA_DATA
DESCRIPTOR.message_types_by_name['ArtifactMetadata'] = _ARTIFACTMETADATA
DESCRIPTOR.message_types_by_name['ArtifactMetadataGlslShaderJob'] = _ARTIFACTMETADATAGLSLSHADERJOB
DESCRIPTOR.message_types_by_name['ArtifactMetadataGlslReduction'] = _ARTIFACTMETADATAGLSLREDUCTION
DESCRIPTOR.message_types_by_name['ArtifactMetadataSpirvShaderJob'] = _ARTIFACTMETADATASPIRVSHADERJOB
DESCRIPTOR.message_types_by_name['ArtifactMetadataAmberJob'] = _ARTIFACTMETADATAAMBERJOB

ArtifactMetadata = _reflection.GeneratedProtocolMessageType('ArtifactMetadata', (_message.Message,), dict(

  Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
    DESCRIPTOR = _ARTIFACTMETADATA_DATA,
    __module__ = 'artifact_pb2'
    # @@protoc_insertion_point(class_scope:ArtifactMetadata.Data)
    ))
  ,
  DESCRIPTOR = _ARTIFACTMETADATA,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:ArtifactMetadata)
  ))
_sym_db.RegisterMessage(ArtifactMetadata)
_sym_db.RegisterMessage(ArtifactMetadata.Data)

ArtifactMetadataGlslShaderJob = _reflection.GeneratedProtocolMessageType('ArtifactMetadataGlslShaderJob', (_message.Message,), dict(
  DESCRIPTOR = _ARTIFACTMETADATAGLSLSHADERJOB,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:ArtifactMetadataGlslShaderJob)
  ))
_sym_db.RegisterMessage(ArtifactMetadataGlslShaderJob)

ArtifactMetadataGlslReduction = _reflection.GeneratedProtocolMessageType('ArtifactMetadataGlslReduction', (_message.Message,), dict(
  DESCRIPTOR = _ARTIFACTMETADATAGLSLREDUCTION,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:ArtifactMetadataGlslReduction)
  ))
_sym_db.RegisterMessage(ArtifactMetadataGlslReduction)

ArtifactMetadataSpirvShaderJob = _reflection.GeneratedProtocolMessageType('ArtifactMetadataSpirvShaderJob', (_message.Message,), dict(
  DESCRIPTOR = _ARTIFACTMETADATASPIRVSHADERJOB,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:ArtifactMetadataSpirvShaderJob)
  ))
_sym_db.RegisterMessage(ArtifactMetadataSpirvShaderJob)

ArtifactMetadataAmberJob = _reflection.GeneratedProtocolMessageType('ArtifactMetadataAmberJob', (_message.Message,), dict(
  DESCRIPTOR = _ARTIFACTMETADATAAMBERJOB,
  __module__ = 'artifact_pb2'
  # @@protoc_insertion_point(class_scope:ArtifactMetadataAmberJob)
  ))
_sym_db.RegisterMessage(ArtifactMetadataAmberJob)


# @@protoc_insertion_point(module_scope)
