# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recipe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import artifact_pb2 as artifact__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recipe.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0crecipe.proto\x1a\x0c\x63ommon.proto\x1a\x0e\x61rtifact.proto\"\xc4\x01\n\x06Recipe\x12!\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x0e.RecipeCommandH\x00\x12S\n#glsl_shader_job_to_spirv_shader_job\x18\x02 \x01(\x0b\x32$.RecipeGlslShaderJobToSpirvShaderJobH\x00\x12\x38\n\x14spirv_shader_job_opt\x18\x03 \x01(\x0b\x32\x18.RecipeSpirvShaderJobOptH\x00\x42\x08\n\x06recipe\" \n\rRecipeCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x03(\t\"k\n#RecipeGlslShaderJobToSpirvShaderJob\x12 \n\x18glsl_shader_job_artifact\x18\x01 \x01(\t\x12\"\n\x1aglslang_validator_artifact\x18\x02 \x01(\t\"p\n\x17RecipeSpirvShaderJobOpt\x12!\n\x19spirv_shader_job_artifact\x18\x01 \x01(\t\x12\x16\n\x0espirv_opt_args\x18\x02 \x03(\t\x12\x1a\n\x12spirv_opt_artifact\x18\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,artifact__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RECIPE = _descriptor.Descriptor(
  name='Recipe',
  full_name='Recipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='Recipe.command', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glsl_shader_job_to_spirv_shader_job', full_name='Recipe.glsl_shader_job_to_spirv_shader_job', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spirv_shader_job_opt', full_name='Recipe.spirv_shader_job_opt', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='recipe', full_name='Recipe.recipe',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=47,
  serialized_end=243,
)


_RECIPECOMMAND = _descriptor.Descriptor(
  name='RecipeCommand',
  full_name='RecipeCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='RecipeCommand.command', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=277,
)


_RECIPEGLSLSHADERJOBTOSPIRVSHADERJOB = _descriptor.Descriptor(
  name='RecipeGlslShaderJobToSpirvShaderJob',
  full_name='RecipeGlslShaderJobToSpirvShaderJob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='glsl_shader_job_artifact', full_name='RecipeGlslShaderJobToSpirvShaderJob.glsl_shader_job_artifact', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glslang_validator_artifact', full_name='RecipeGlslShaderJobToSpirvShaderJob.glslang_validator_artifact', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=386,
)


_RECIPESPIRVSHADERJOBOPT = _descriptor.Descriptor(
  name='RecipeSpirvShaderJobOpt',
  full_name='RecipeSpirvShaderJobOpt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spirv_shader_job_artifact', full_name='RecipeSpirvShaderJobOpt.spirv_shader_job_artifact', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spirv_opt_args', full_name='RecipeSpirvShaderJobOpt.spirv_opt_args', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spirv_opt_artifact', full_name='RecipeSpirvShaderJobOpt.spirv_opt_artifact', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=500,
)

_RECIPE.fields_by_name['command'].message_type = _RECIPECOMMAND
_RECIPE.fields_by_name['glsl_shader_job_to_spirv_shader_job'].message_type = _RECIPEGLSLSHADERJOBTOSPIRVSHADERJOB
_RECIPE.fields_by_name['spirv_shader_job_opt'].message_type = _RECIPESPIRVSHADERJOBOPT
_RECIPE.oneofs_by_name['recipe'].fields.append(
  _RECIPE.fields_by_name['command'])
_RECIPE.fields_by_name['command'].containing_oneof = _RECIPE.oneofs_by_name['recipe']
_RECIPE.oneofs_by_name['recipe'].fields.append(
  _RECIPE.fields_by_name['glsl_shader_job_to_spirv_shader_job'])
_RECIPE.fields_by_name['glsl_shader_job_to_spirv_shader_job'].containing_oneof = _RECIPE.oneofs_by_name['recipe']
_RECIPE.oneofs_by_name['recipe'].fields.append(
  _RECIPE.fields_by_name['spirv_shader_job_opt'])
_RECIPE.fields_by_name['spirv_shader_job_opt'].containing_oneof = _RECIPE.oneofs_by_name['recipe']
DESCRIPTOR.message_types_by_name['Recipe'] = _RECIPE
DESCRIPTOR.message_types_by_name['RecipeCommand'] = _RECIPECOMMAND
DESCRIPTOR.message_types_by_name['RecipeGlslShaderJobToSpirvShaderJob'] = _RECIPEGLSLSHADERJOBTOSPIRVSHADERJOB
DESCRIPTOR.message_types_by_name['RecipeSpirvShaderJobOpt'] = _RECIPESPIRVSHADERJOBOPT

Recipe = _reflection.GeneratedProtocolMessageType('Recipe', (_message.Message,), dict(
  DESCRIPTOR = _RECIPE,
  __module__ = 'recipe_pb2'
  # @@protoc_insertion_point(class_scope:Recipe)
  ))
_sym_db.RegisterMessage(Recipe)

RecipeCommand = _reflection.GeneratedProtocolMessageType('RecipeCommand', (_message.Message,), dict(
  DESCRIPTOR = _RECIPECOMMAND,
  __module__ = 'recipe_pb2'
  # @@protoc_insertion_point(class_scope:RecipeCommand)
  ))
_sym_db.RegisterMessage(RecipeCommand)

RecipeGlslShaderJobToSpirvShaderJob = _reflection.GeneratedProtocolMessageType('RecipeGlslShaderJobToSpirvShaderJob', (_message.Message,), dict(
  DESCRIPTOR = _RECIPEGLSLSHADERJOBTOSPIRVSHADERJOB,
  __module__ = 'recipe_pb2'
  # @@protoc_insertion_point(class_scope:RecipeGlslShaderJobToSpirvShaderJob)
  ))
_sym_db.RegisterMessage(RecipeGlslShaderJobToSpirvShaderJob)

RecipeSpirvShaderJobOpt = _reflection.GeneratedProtocolMessageType('RecipeSpirvShaderJobOpt', (_message.Message,), dict(
  DESCRIPTOR = _RECIPESPIRVSHADERJOBOPT,
  __module__ = 'recipe_pb2'
  # @@protoc_insertion_point(class_scope:RecipeSpirvShaderJobOpt)
  ))
_sym_db.RegisterMessage(RecipeSpirvShaderJobOpt)


# @@protoc_insertion_point(module_scope)
